### ISSUE TITLE
Deploy to heroku

### ISSUE THREAD

**Issue by avdata99** [OpenDataCordoba/coinor#1]
No pude

**Comment by avilaton** [comment]
Cierro. Solo necesitabamos poner el proceso `web` en ON en el dashboard o también desde la línea de comandos con ps:scale o algo asi.
![screencapture-dashboard-heroku-com-apps-coinor-resources-1467647312667](https://cloud.githubusercontent.com/assets/2209022/16565736/a6336f20-41e5-11e6-8388-16806711ec95.png)

**Comment by avdata99** [comment]
aggggwgwggwgwhhhhhwhwhwhwhhwh

**Comment by avilaton** [comment]
Jajajajaja
