### ISSUE TITLE
Error al cargar

### ISSUE THREAD

**Issue by rikh1975** [OpenDataCordoba/coinor#2]
UnicodeEncodeError at /admin/data/persona/add/

'ascii' codec can't encode character u'\xf3' in position 11: ordinal not in range(128)

Request Method:     POST
Request URL:    http://coinor.herokuapp.com/admin/data/persona/add/
Django Version:     1.9.7
Exception Type:     UnicodeEncodeError
Exception Value:    

'ascii' codec can't encode character u'\xf3' in position 11: ordinal not in range(128)

Exception Location:     /app/.heroku/python/lib/python2.7/site-packages/django/utils/encoding.py in force_text, line 80
Python Executable:  /app/.heroku/python/bin/python
Python Version:     2.7.11
Python Path:    

['/app',
 '/app/.heroku/python/bin',
 '/app/.heroku/python/lib/python2.7/site-packages/setuptools-23.1.0-py2.7.egg',
 '/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg',
 '/app',
 '/app/.heroku/python/lib/python27.zip',
 '/app/.heroku/python/lib/python2.7',
 '/app/.heroku/python/lib/python2.7/plat-linux2',
 '/app/.heroku/python/lib/python2.7/lib-tk',
 '/app/.heroku/python/lib/python2.7/lib-old',
 '/app/.heroku/python/lib/python2.7/lib-dynload',
 '/app/.heroku/python/lib/python2.7/site-packages']

Server time:    Mon, 25 Jul 2016 20:42:22 +0000
Unicode error hint

The string that could not be encoded/decoded was: bal López
Traceback Switch to copy-and-paste view

```
/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py in get_response
```

Preguntas:
1- Hay forma de cargar una base de cvs con datos?
2- Una vez que cargo los datos de relaciones como hago las visualizaciones? 
(Ejemplo: https://vis.occrp.org/)

**Comment by avdata99** [comment]
Debe ser un acento o caracter especial.
No usarlos por ahora hasta que se resuelva

**Comment by avilaton** [comment]
cambia `__str__` por `__unicode__` en los modelos. Cerrado.
